### ISSUE TITLE
NetlifyCMS string list doesn't support whitespaces

### ISSUE THREAD

**Issue by patricoferris** [ocaml/ood#12]
Currently the default NetlifyCMS widget for lists and strings only allows comma-separated values but crucially the strings cannot contain spaces. This is problematic for author/people lists which need spaces. There are two workarounds:

 1. Extend `lib_netlify` to support custom widgets and use https://github.com/netlify/netlify-cms/issues/4646 
 2. Turn an `author` or `person` into an object with a name field. This seems the best and easiest solution and would leave the door open for adding extra information, for example an optional `affiliation` field for `authors` in `papers.yml`.

Resolving this issue with (2) would also be nice experiment of the workflow of modifying existing data that is currently being used by v3, updating type definitions and porting back to the web front-end.

**Comment by tmattio** [comment]
Closing as we removed Netlify
